modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = ""
license="MIT"
[[mods]]
modId = "mtstorage"
version = "${version}"
displayName = "MassTech Digital Storage"
displayURL = ""
logoFile = "logo.png"
authors = "HybridAvenger69"
description = '''
An elegant solution to your hoarding problem
'''